### PR TITLE
SL3.Exp take in array or list

### PR DESCRIPTION
**Pull request by PDeco**
Slight change to SL3 class method Exp to allow xi to be a list OR an array

### CODE REVIEW

**Comment by sdahdah** [comment]
https://numpy.org/doc/stable/reference/generated/numpy.asarray.html

**Comment by sdahdah** [comment]
Is this behaviour consistent with the rest of the lib? If not, can you change the other groups to match? @CharlesCossette what do you think?

**Comment by CharlesCossette** [comment]
> Is this behaviour consistent with the rest of the lib? If not, can you change the other groups to match? @CharlesCossette what do you think?

Yup. I've been implementing this everywhere as I go but should do one global pass to make sure everything that's supposed to accept a "vector" has this trick

**Comment by sdahdah** [comment]
Good opportunity for a big parametrized unit test with `@pytest.mark.parametrize()`

**Review by CharlesCossette — APPROVED** [review]

**Pull request merged**
